kbc-itw/BookChain

- build.gradle
> 依存関係にfabric-sdkを追加

- .gitignore
- index.ts
- package-lock.json
- package.json
- tsconfig.json
+ mocha, chai, sinon, istanbul, remap-istanbulならびに型定義のインストールとnpm testの有効化
+ source-map-supportの型定義インストールならびに有効化
`npm test`でtscしてmochaでテストしistanbulでカバレッジを出してremap-istanbulでtsでのカバレッジにリマップします。
> 開発環境セットアップ

- app/util.ts
> [clean] util.tsの構文エラーを修正

- app/roomWebSocket.ts
- app/router/ownership.ts
- app/router/rooms.ts
- app/router/tradings.ts
- app/router/user.ts
getTransactionID()におけるreturn文は到達不能コードであるため、コンパイルエラーになる。
削除しても問題がないため、削除した。
> [clean] 不要なので削除

- app/roomWebSocket.ts
- app/router/rooms.ts
- test/router/rooms.spec.ts
> roomPoolを関数の引数として引き渡すことにした

- app/config/IWSConfig.ts
- app/roomWebSocket.ts
- config/deployment.json
- config/development.json
- config/test.json
- test/roomWebSocket.spec.ts
+ ws.Serverが非同期処理であることへの対応
+ ws.Serverへ渡すオプションが不足であったことへの対応
+ サンプルとしてspecの作成
> roomWebSocket修正

- app/roomWebSocket.ts
url.parseの第二引数にtrueを追加
socket.send時にJSON.stringifyをしていない箇所の修正
validateメソッド内の条件分修正
コネクションが接続できないエラー
> [clean] roomWebSocket修正

- app/roomWebSocket.ts
> url.parseからtrueが消えてた問題

- app/roomWebSocket.ts
> 既に閉じている部屋に接続しようとされた場合、コネクションが成立する問題の修正

- app/roomWebSocket.ts
> パラメータ名のミスを修正

- app/roomWebSocket.ts
> commitRentalを削除

- app/roomWebSocket.ts
> [update] validateをexport

- app/authenticator.ts
- app/bootstrap.ts
- app/router/authenticate.ts
- app/router/user.ts
> クライアントをサーブできるように

- config/secrets-template.json
キー名が間違っていたのと、足りないものがあったため修正
@wamekukyouzin きいとるか！！！！
> 設定ファイルのテンプレートのキー値の修正

- app/roomWebSocket.ts
- app/router/rooms.ts
- app/router/tradings.ts
> locatorであるところに対し、アンエスケープ

- app/authenticator.ts
- app/router/user.ts
> NODE_ENVの値が古かったのを修正

- config/default.json
> stdoutを出力先として追加

- config/secrets-template.json
ドッカーコンテナ　platformのデフォルト値を設定しておく
> platformのデフォルトに合わせて設定

- app/auth-db.ts
auth-dbのエラー処理と正常処理でif文が逆でした！！！！！！
> エラーハンドリングが逆だったのを修正

- app/auth-db.ts
update目的でinsert呼び出すときは第２引数にID渡さないとだめでした
> nanoのアップデートの呼び出し方にまちがいがあったので修正

- app/auth-db.ts
- app/bootstrap.ts
- app/router/register.ts
- test/router/register.spec.ts
> registerlocalinfoの引数の型を必要なものだけに修正

- app/bootstrap.ts
- app/router/register.ts
- app/router/user.ts
+ sendを連続して行っている問題
+ ユーザ登録後に登録した情報をchaincodeに突っ込んでいない問題
> Userルータの問題

- app/chaincode-connection.ts
> chaincodeInvokeにおけるタイムアウトの削除

- app/router/user.ts
fcn'getUser'に対しhostとidを渡していたが、要求するのはLocatorであるのでそのようにした
> /user/host/idで呼ばれるgetUserListが要求するのはLocatorであるので修正

- app/chaincode-connection.ts
void型にしててreturnしてないんだからそりゃ何も返ってこない
> chaincodeInvokeが何も返してこない問題

- app/roomWebSocket.ts
- index.ts
> httpならびにwebSocketサーバのlistenのホスト指定を削除

- app/auth-db.ts
取ってきたらまずいかと思ってたけど、取ってこないとまずいやつでした
> _revが必要だった修正

- app/router/ownership.ts
> getOwnerShipList

- app/router/rooms.ts
> chaincodeへのinvokeは返却値ないようなのでこちらで返却値を生成するように

- app/roomWebSocket.ts
- app/router/rooms.ts
- app/router/tradings.ts
unescapeではパーセントエンコードされた文字列を処理できない
> ロケータに対してunescapeしていたところをdecodeURIComponentに修正

- app/roomWebSocket.ts
- app/router/rooms.ts
- test/roomWebSocket.spec.ts
> 部屋がプールされてない問題

- index.ts
> パスが間違っていた問題
